name: "auth"
mode: "test"
port: 80
host: "0.0.0.0"
base_url: "http://z-3sp:80"
mysql:
  host: "127.0.0.1"
  port: 3307
  user: "root"
  passwd: "Fndo123456"
  dbname: "uc"
  max_open_conns: 10
  max_idle_conns: 5
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  passwd: ""
  pool_size: 50
