apiVersion: v1
kind: Secret
metadata:
  name: z-uc-secrets
type: Opaque
stringData:
  jwt-secret: "REAAW332LPPPPPEC00S++++++SDEDSSDFCCCCCC_____FFRFDSSDS"
  mysql-user: "root"
  mysql-passwd: "Fndo123456"
  mysql-dbname: "z_uc"
  redis-passwd: "fd88-"
